import 'package:country_quiz/fix_pub_lib/country_pickers_1.1.0_fix/country.dart';
import 'package:flutter/material.dart';
import 'package:country_quiz/l10n/l10n.dart';

List<Country> countryList(BuildContext context) {
  return [
    Country(
      continents: [L10n.of(context).europeForSearchCategory],
      isoCode: "AD",
      phoneCode: "376",
      name: L10n.of(context).andorraInCountryCategory,
      nameForJpSearch: "アンドラ",
      iso3Code: "AND",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "AE",
      phoneCode: "971",
      name: L10n.of(context).areInCountryCategory,
      nameForJpSearch: "アラブシュチョウコクレンポウ",
      iso3Code: "ARE",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "AF",
      phoneCode: "93",
      name: L10n.of(context).afghanistanInCountryCategory,
      nameForJpSearch: "アフガニスタン",
      iso3Code: "AFG",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "AG",
      phoneCode: "1-268",
      name: L10n.of(context).atgInCountryCategory,
      nameForJpSearch: "アンティグア・バーブーダ",
      iso3Code: "ATG",
    ),
//  Country(
//    continents: [""], isoCode: "AI",
//    phoneCode: "1-264",
//    name: "Anguilla",
//    nameForJpSearch: "アンギラ",
//    iso3Code: "AIA",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "AL",
      phoneCode: "355",
      name: L10n.of(context).albaniaInCountryCategory,
      nameForJpSearch: "アルバニア",
      iso3Code: "ALB",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "AM",
      phoneCode: "374",
      name: L10n.of(context).armeniaInCountryCategory,
      nameForJpSearch: "アルメニア",
      iso3Code: "ARM",
    ),
//  Country(
//    continents: [""], isoCode: "AN",
//    phoneCode: "599",
//    name: "Netherlands Antilles",
//    nameForJpSearch: "",
//    iso3Code: "AN",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "AO",
      phoneCode: "244",
      name: L10n.of(context).angolaInCountryCategory,
      nameForJpSearch: "アンゴラ",
      iso3Code: "AGO",
    ),
//  Country(
//    continents: [""], isoCode: "AQ",
//    phoneCode: "672",
//    name: "Antarctica",
//    nameForJpSearch: "南極",
//    iso3Code: "ATA",
//  ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "AR",
      phoneCode: "54",
      name: L10n.of(context).argentinaInCountryCategory,
      nameForJpSearch: "アルゼンチン",
      iso3Code: "ARG",
    ),
//  Country(
//    continents: [""], isoCode: "AS",
//    phoneCode: "1-684",
//    name: "American Samoa",
//    nameForJpSearch: "アメリカ領サモア",
//    iso3Code: "ASM",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory],
      isoCode: "AT",
      phoneCode: "43",
      name: L10n.of(context).austriaInCountryCategory,
      nameForJpSearch: "オーストリア",
      iso3Code: "AUT",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "AU",
      phoneCode: "61",
      name: L10n.of(context).australiaInCountryCategory,
      nameForJpSearch: "オーストラリア",
      iso3Code: "AUS",
    ),
//  Country(
//    continents: [""], isoCode: "AW",
//    phoneCode: "297",
//    name: "Aruba",
//    nameForJpSearch: "アルバ",
//    iso3Code: "ABW",
//  ),
//  Country(
//    continents: [""], isoCode: "AX",
//    phoneCode: "358",
//    name: "Åland Islands",
//    nameForJpSearch: "オーランド諸島",
//    iso3Code: "ALA",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "AZ",
      phoneCode: "994",
      name: L10n.of(context).azerbaijanInCountryCategory,
      nameForJpSearch: "アゼルバイジャン",
      iso3Code: "AZE",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "BA",
      phoneCode: "387",
      name: L10n.of(context).bihInCountryCategory,
      nameForJpSearch: "ボスニア・ヘルツェゴビナ",
      iso3Code: "BIH",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "BB",
      phoneCode: "1-246",
      name: L10n.of(context).barbadosInCountryCategory,
      nameForJpSearch: "バルバドス",
      iso3Code: "BRB",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "BD",
      phoneCode: "880",
      name: L10n.of(context).bangladeshInCountryCategory,
      nameForJpSearch: "バングラデシュ",
      iso3Code: "BGD",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "BE",
      phoneCode: "32",
      name: L10n.of(context).belgiumInCountryCategory,
      nameForJpSearch: "ベルギー",
      iso3Code: "BEL",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "BF",
      phoneCode: "226",
      name: L10n.of(context).bfaInCountryCategory,
      nameForJpSearch:"ブルキナファソ",
      iso3Code: "BFA",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "BG",
      phoneCode: "359",
      name: L10n.of(context).bulgariaInCountryCategory,
      nameForJpSearch: "ブルガリア",
      iso3Code: "BGR",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "BH",
      phoneCode: "973",
      name: L10n.of(context).bahrainInCountryCategory,
      nameForJpSearch: "バーレーン",
      iso3Code: "BHR",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "BI",
      phoneCode: "257",
      name: L10n.of(context).burundiInCountryCategory,
      nameForJpSearch: "ブルンジ",
      iso3Code: "BDI",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "BJ",
      phoneCode: "229",
      name: L10n.of(context).beninInCountryCategory,
      nameForJpSearch: "ベナン",
      iso3Code: "BEN",
    ),
//  Country(
//    continents: [""], isoCode: "BL",
//    phoneCode: "590",
//    name: "Saint Barthélemy",
//    nameForJpSearch: "サン・バルテルミー",
//    iso3Code: "BLM",
//  ),
//  Country(
//    continents: [""], isoCode: "BM",
//    phoneCode: "1-441",
//    name: "Bermuda",
//    nameForJpSearch: "バミューダ",
//    iso3Code: "BMU",
//  ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "BN",
      phoneCode: "673",
      name: L10n.of(context).brnInCountryCategory,
//    nameForJpSearch: "ブルネイダルサラーム",
      nameForJpSearch: "ブルネイ",
      iso3Code: "BRN",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "BO",
      phoneCode: "591",
      name: L10n.of(context).bolInCountryCategory,
//    nameForJpSearch: "ボリビア多民族国",
      nameForJpSearch: "ボリビア",
      iso3Code: "BOL",
    ),
//  Country(
//    continents: [""], isoCode: "BQ",
//    phoneCode: "599",
//    name: "Caribbean Netherlands",
//    nameForJpSearch: "カリブ・オランダ",
//    iso3Code: "BES",
//  ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "BR",
      phoneCode: "55",
      name: L10n.of(context).brazilInCountryCategory,
      nameForJpSearch: "ブラジル",
      iso3Code: "BRA",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "BS",
      phoneCode: "1-242",
      name: L10n.of(context).bahamasInCountryCategory,
      nameForJpSearch: "バハマ",
      iso3Code: "BHS",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "BT",
      phoneCode: "975",
      name: L10n.of(context).bhutanInCountryCategory,
      nameForJpSearch: "ブータンオウコク",
      iso3Code: "BTN",
    ),
//  Country(
//    continents: [""], isoCode: "BV",
//    phoneCode: "47",
//    name: "Bouvet Island",
//    nameForJpSearch: "ブーベ島",
//    iso3Code: "BVT",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "BW",
      phoneCode: "267",
      name: L10n.of(context).botswanaInCountryCategory,
      nameForJpSearch: "ボツワナ",
      iso3Code: "BWA",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "BY",
      phoneCode: "375",
      name: L10n.of(context).belarusInCountryCategory,
      nameForJpSearch: "ベラルーシ",
      iso3Code: "BLR",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "BZ",
      phoneCode: "501",
      name: L10n.of(context).belizeInCountryCategory,
      nameForJpSearch: "ベリーズ",
      iso3Code: "BLZ",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "CA",
      phoneCode: "1",
      name: L10n.of(context).canadaInCountryCategory,
      nameForJpSearch: "カナダ",
      iso3Code: "CAN",
    ),
//  Country(
//    continents: [""], isoCode: "CC",
//    phoneCode: "61",
//    name: "Cocos (Keeling) Islands",
//    nameForJpSearch: "ココス諸島",
//    iso3Code: "CCK",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "CD",
      phoneCode: "243",
      name: L10n.of(context).codInCountryCategory,
      nameForJpSearch: "コンゴミンシュキョウワコク",
      iso3Code: "COD",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "CF",
      phoneCode: "236",
      name: L10n.of(context).cafInCountryCategory,
      nameForJpSearch: "チュウオウアフリカキョウワコク",
      iso3Code: "CAF",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "CG",
      phoneCode: "242",
      name: L10n.of(context).cogInCountryCategory,
//    nameForJpSearch: "コンゴ共和国",
      nameForJpSearch: "コンゴ",
      iso3Code: "COG",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "CH",
      phoneCode: "41",
      name: L10n.of(context).switzerlandInCountryCategory,
      nameForJpSearch: "スイス",
      iso3Code: "CHE",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "CI",
      phoneCode: "225",
      name: L10n.of(context).civInCountryCategory,
      nameForJpSearch: "コートジボワール",
      iso3Code: "CIV",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory],
      isoCode: "CK",
      phoneCode: "682",
      name: L10n.of(context).cokInCountryCategory,
      nameForJpSearch: "クックショトウ",
      iso3Code: "COK",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "CL",
      phoneCode: "56",
      name: L10n.of(context).chileInCountryCategory,
      nameForJpSearch: "チリ",
      iso3Code: "CHL",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "CM",
      phoneCode: "237",
      name: L10n.of(context).cameroonInCountryCategory,
      nameForJpSearch: "カメルーン",
      iso3Code: "CMR",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "CN",
      phoneCode: "86",
      name: L10n.of(context).chinaInCountryCategory,
      nameForJpSearch: "チュウゴク",
      iso3Code: "CHN",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "CO",
      phoneCode: "57",
      name: L10n.of(context).colombiaInCountryCategory,
      nameForJpSearch: "コロンビア",
      iso3Code: "COL",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "CR",
      phoneCode: "506",
      name: L10n.of(context).criInCountryCategory,
      nameForJpSearch: "コスタリカ",
      iso3Code: "CRI",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "CU",
      phoneCode: "53",
      name: L10n.of(context).cubaInCountryCategory,
      nameForJpSearch: "キューバ",
      iso3Code: "CUB",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "CV",
      phoneCode: "238",
      name: L10n.of(context).cpvInCountryCategory,
      nameForJpSearch: "カーボベルデ",
      iso3Code: "CPV",
    ),
//  Country(
//    continents: [""], isoCode: "CW",
//    phoneCode: "599",
//    name: "Curaçao",
//    nameForJpSearch: "キュラソー",
//    iso3Code: "CUW",
//  ),
//  Country(
//    continents: [""], isoCode: "CX",
//    phoneCode: "61",
//    name: "Christmas Island",
//    nameForJpSearch: "クリスマス島",
//    iso3Code: "CXR",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "CY",
      phoneCode: "357",
      name: L10n.of(context).cyprusInCountryCategory,
      nameForJpSearch: "キプロス",
      iso3Code: "CYP",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "CZ",
      phoneCode: "420",
      name: L10n.of(context).czeInCountryCategory,
//    nameForJpSearch: "チェコ共和国",
      nameForJpSearch: "チェコ",
      iso3Code: "CZE",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "DE",
      phoneCode: "49",
      name: L10n.of(context).germanyInCountryCategory,
      nameForJpSearch: "ドイツ",
      iso3Code: "DEU",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "DJ",
      phoneCode: "253",
      name: L10n.of(context).djiboutiInCountryCategory,
      nameForJpSearch: "ジブチ",
      iso3Code: "DJI",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "DK",
      phoneCode: "45",
      name: L10n.of(context).denmarkInCountryCategory,
      nameForJpSearch: "デンマーク",
      iso3Code: "DNK",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "DM",
      phoneCode: "1-767",
      name: L10n.of(context).dominicaInCountryCategory,
//    nameForJpSearch: "ドミニカ国",
      nameForJpSearch: "ドミニカ",
      iso3Code: "DMA",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "DO",
      phoneCode: "1-849",
      name: L10n.of(context).domInCountryCategory,
      nameForJpSearch: "ドミニカキョウワコク",
      iso3Code: "DOM",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "DZ",
      phoneCode: "213",
      name: L10n.of(context).algeriaInCountryCategory,
      nameForJpSearch: "アルジェリア",
      iso3Code: "DZA",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "EC",
      phoneCode: "593",
      name: L10n.of(context).ecuadorInCountryCategory,
      nameForJpSearch: "エクアドル",
      iso3Code: "ECU",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "EE",
      phoneCode: "372",
      name: L10n.of(context).estoniaInCountryCategory,
      nameForJpSearch: "エストニア",
      iso3Code: "EST",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "EG",
      phoneCode: "20",
      name: L10n.of(context).egyptInCountryCategory,
      nameForJpSearch: "エジプト",
      iso3Code: "EGY",
    ),
//  Country(
//    continents: [""], isoCode: "EH",
//    phoneCode: "212",
//    name: "Western Sahara",
//    nameForJpSearch: "西サハラ",
//    iso3Code: "ESH",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "ER",
      phoneCode: "291",
      name: L10n.of(context).eritreaInCountryCategory,
      nameForJpSearch: "エリトリア",
      iso3Code: "ERI",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "ES",
      phoneCode: "34",
      name: L10n.of(context).spainInCountryCategory,
      nameForJpSearch: "スペイン",
      iso3Code: "ESP",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "ET",
      phoneCode: "251",
      name: L10n.of(context).ethiopiaInCountryCategory,
      nameForJpSearch: "エチオピア",
      iso3Code: "ETH",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "FI",
      phoneCode: "358",
      name: L10n.of(context).finlandInCountryCategory,
      nameForJpSearch: "フィンランド",
      iso3Code: "FIN",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory],
      isoCode: "FJ",
      phoneCode: "679",
      name: L10n.of(context).fijiInCountryCategory,
      nameForJpSearch: "フィジー",
      iso3Code: "FJI",
    ),
//  Country(
//    continents: [""], isoCode: "FK",
//    phoneCode: "500",
//    name: "Falkland Islands (Malvinas)",
//    nameForJpSearch: "フォークランド諸島",
//    iso3Code: "FLK",
//  ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "FM",
      phoneCode: "691",
      name: L10n.of(context).fsmInCountryCategory,
      nameForJpSearch: "ミクロネシアレンポウ",
      iso3Code: "FSM",
    ),
//  Country(
//    continents: [""], isoCode: "FO",
//    phoneCode: "298",
//    name: "Faroe Islands",
//    nameForJpSearch: "フェロー諸島",
//    iso3Code: "FRO",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "FR",
      phoneCode: "33",
      name: L10n.of(context).franceInCountryCategory,
      nameForJpSearch: "フランス",
      iso3Code: "FRA",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "GA",
      phoneCode: "241",
      name: L10n.of(context).gabonInCountryCategory,
      nameForJpSearch: "ガボン",
      iso3Code: "GAB",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "GB",
      phoneCode: "44",
      name: L10n.of(context).gbrInCountryCategory,
      nameForJpSearch: "イギリス",
      iso3Code: "GBR",
    ),
    // Country(
    //   continents: [""], isoCode: "GB-ENG",
    //   phoneCode: "44",
    //   name: "England",
    //   nameForJpSearch: "イングランド",
    //   iso3Code: "GBR",
    // ),
    // Country(
    //   continents: [""], isoCode: "GB-NIR",
    //   phoneCode: "44",
    //   name: "Northern Ireland",
    //   nameForJpSearch: "北アイルランド",
    //   iso3Code: "GBR",
    // ),
    // Country(
    //   continents: [""], isoCode: "GB-SCT",
    //   phoneCode: "44",
    //   name: "Scotland",
    //   nameForJpSearch: "スコットランド",
    //   iso3Code: "GBR",
    // ),
    // Country(
    //   continents: [""], isoCode: "GB-WLS",
    //   phoneCode: "44",
    //   name: "Wales",
    //   nameForJpSearch: "ウェールズ",
    //   iso3Code: "GBR",
    // ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "GD",
      phoneCode: "1-473",
      name: L10n.of(context).grenadaInCountryCategory,
      nameForJpSearch: "グレナダ",
      iso3Code: "GRD",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory, L10n.of(context).europeForSearchCategory], isoCode: "GE",
      phoneCode: "995",
      name: L10n.of(context).georgiaInCountryCategory,
      nameForJpSearch: "ジョージア",
      iso3Code: "GEO",
    ),
//  Country(
//    continents: [""], isoCode: "GF",
//    phoneCode: "594",
//    name: "French Guiana",
//    nameForJpSearch: "フランス領ギアナ",
//    iso3Code: "GUF",
//  ),
//  Country(
//    continents: [""], isoCode: "GG",
//    phoneCode: "44-1481",
//    name: "Guernsey",
//    nameForJpSearch: "ガーンジー",
//    iso3Code: "GGY",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "GH",
      phoneCode: "233",
      name: L10n.of(context).ghanaInCountryCategory,
      nameForJpSearch: "ガーナ",
      iso3Code: "GHA",
    ),
//  Country(
//    continents: [""], isoCode: "GI",
//    phoneCode: "350",
//    name: "Gibraltar",
//    nameForJpSearch: "ジブラルタル",
//    iso3Code: "GIB",
//  ),
//  Country(
//    continents: [""], isoCode: "GL",
//    phoneCode: "299",
//    name: "Greenland",
//    nameForJpSearch: "グリーンランド",
//    iso3Code: "GRL",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "GM",
      phoneCode: "220",
      name: L10n.of(context).gambiaInCountryCategory,
      nameForJpSearch: "ガンビア",
      iso3Code: "GMB",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "GN",
      phoneCode: "224",
      name: L10n.of(context).guineaInCountryCategory,
      nameForJpSearch: "ギニア",
      iso3Code: "GIN",
    ),
//  Country(
//    continents: [""], isoCode: "GP",
//    phoneCode: "590",
//    name: "Guadeloupe",
//    nameForJpSearch: "グアドループ",
//    iso3Code: "GLP",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "GQ",
      phoneCode: "240",
      name: L10n.of(context).gnqInCountryCategory,
      nameForJpSearch: "セキドウギニア",
      iso3Code: "GNQ",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "GR",
      phoneCode: "30",
      name: L10n.of(context).greeceInCountryCategory,
      nameForJpSearch: "ギリシャ",
      iso3Code: "GRC",
    ),
//  Country(
//    continents: [""], isoCode: "GS",
//    phoneCode: "500",
//    name: "South Georgia and the South Sandwich Islands",
//    nameForJpSearch: "サウスジョージア・サウスサンドウィッチ諸島",
//    iso3Code: "SGS",
//  ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "GT",
      phoneCode: "502",
      name: L10n.of(context).guatemalaInCountryCategory,
      nameForJpSearch: "グアテマラ",
      iso3Code: "GTM",
    ),
    // Country(
    //   continents: [""], isoCode: "GU",
    //   phoneCode: "1-671",
    //   name: "Guam",
    //   nameForJpSearch: "グアム",
    //   iso3Code: "GUM",
    // ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "GW",
      phoneCode: "245",
      name: L10n.of(context).gnbInCountryCategory,
      nameForJpSearch: "ギニアビサウ",
      iso3Code: "GNB",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "GY",
      phoneCode: "592",
      name: L10n.of(context).guyanaInCountryCategory,
      nameForJpSearch: "ガイアナ",
      iso3Code: "GUY",
    ),
//  Country(
//    continents: [""], isoCode: "HK",
//    phoneCode: "852",
//    name: "Hong Kong",
//    nameForJpSearch: "香港(中国特別行政区)",
//    iso3Code: "HKG",
//  ),
//  Country(
//    continents: [""], isoCode: "HM",
//    phoneCode: "672",
//    name: "Heard Island and McDonald Islands",
//    nameForJpSearch: "ハード島とマクドナルド諸島",
//    iso3Code: "HMD",
//  ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "HN",
      phoneCode: "504",
      name: L10n.of(context).hondurasInCountryCategory,
      nameForJpSearch: "ホンジュラス",
      iso3Code: "HND",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "HR",
      phoneCode: "385",
      name: L10n.of(context).croatiaInCountryCategory,
      nameForJpSearch: "クロアチア",
      iso3Code: "HRV",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "HT",
      phoneCode: "509",
      name: L10n.of(context).haitiInCountryCategory,
      nameForJpSearch: "ハイチ",
      iso3Code: "HTI",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "HU",
      phoneCode: "36",
      name: L10n.of(context).hungaryInCountryCategory,
      nameForJpSearch: "ハンガリー",
      iso3Code: "HUN",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "ID",
      phoneCode: "62",
      name: L10n.of(context).indonesiaInCountryCategory,
      nameForJpSearch: "インドネシア",
      iso3Code: "IDN",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "IE",
      phoneCode: "353",
      name: L10n.of(context).irelandInCountryCategory,
      nameForJpSearch: "アイルランド",
      iso3Code: "IRL",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory, L10n.of(context).europeForSearchCategory], isoCode: "IL",
      phoneCode: "972",
      name: L10n.of(context).israelInCountryCategory,
      nameForJpSearch: "イスラエル",
      iso3Code: "ISR",
    ),
//  Country(
//    continents: [""], isoCode: "IM",
//    phoneCode: "44-1624",
//    name: "Isle of Man",
//    nameForJpSearch: "マン島",
//    iso3Code: "IMN",
//  ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "IN",
      phoneCode: "91",
      name: L10n.of(context).indiaInCountryCategory,
      nameForJpSearch: "インド",
      iso3Code: "IND",
    ),
    // Country(
    //   continents: [""], isoCode: "IO",
    //   phoneCode: "246",
    //   name: "British Indian Ocean Territory",
    //   nameForJpSearch: "イギリス領インド洋地域",
    //   iso3Code: "IOT",
    // ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "IQ",
      phoneCode: "964",
      name: L10n.of(context).iraqInCountryCategory,
      nameForJpSearch: "イラク",
      iso3Code: "IRQ",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "IR",
      phoneCode: "98",
      name: L10n.of(context).irnInCountryCategory,
//    nameForJpSearch: "イラン・イスラム共和国",
      nameForJpSearch: "イラン",
      iso3Code: "IRN",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "IS",
      phoneCode: "354",
      name: L10n.of(context).icelandInCountryCategory,
      nameForJpSearch: "アイスランド",
      iso3Code: "ISL",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "IT",
      phoneCode: "39",
      name: L10n.of(context).italyInCountryCategory,
      nameForJpSearch: "イタリア",
      iso3Code: "ITA",
    ),
//  Country(
//    continents: [""], isoCode: "JE",
//    phoneCode: "44-1534",
//    name: "Jersey",
//    nameForJpSearch: "ジャージー",
//    iso3Code: "JEY",
//  ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "JM",
      phoneCode: "1-876",
      name: L10n.of(context).jamaicaInCountryCategory,
      nameForJpSearch: "ジャマイカ",
      iso3Code: "JAM",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "JO",
      phoneCode: "962",
      name: L10n.of(context).jordanInCountryCategory,
      nameForJpSearch: "ヨルダン",
      iso3Code: "JOR",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory],
      isoCode: "JP",
      phoneCode: "81",
      name: L10n.of(context).japanInCountryCategory,
      nameForJpSearch: "ニホン",
      iso3Code: "JPN",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "KE",
      phoneCode: "254",
      name: L10n.of(context).kenyaInCountryCategory,
      nameForJpSearch: "ケニア",
      iso3Code: "KEN",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "KG",
      phoneCode: "996",
      name: L10n.of(context).kyrgyzstanInCountryCategory,
      nameForJpSearch: "キルギス",
      iso3Code: "KGZ",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "KH",
      phoneCode: "855",
      name: L10n.of(context).cambodiaInCountryCategory,
      nameForJpSearch: "カンボジア",
      iso3Code: "KHM",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory],
      isoCode: "KI",
      phoneCode: "686",
      name: L10n.of(context).kiribatiInCountryCategory,
//    nameForJpSearch: "キリバス共和国",
      nameForJpSearch: "キリバス",
      iso3Code: "KIR",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "KM",
      phoneCode: "269",
      name: L10n.of(context).comorosInCountryCategory,
      nameForJpSearch: "コモロ",
      iso3Code: "COM",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "KN",
      phoneCode: "1-869",
      name: L10n.of(context).knaInCountryCategory,
      nameForJpSearch: "セントクリストファー・ネイビス",
      iso3Code: "KNA",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "KP",
      phoneCode: "850",
      name: L10n.of(context).prkInCountryCategory,
      nameForJpSearch: "キタチョウセン",
      iso3Code: "PRK",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory],
      isoCode: "KR",
      phoneCode: "82",
      name: L10n.of(context).korInCountryCategory,
      nameForJpSearch: "カンコク",
      iso3Code: "KOR",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "KW",
      phoneCode: "965",
      name: L10n.of(context).kuwaitInCountryCategory,
      nameForJpSearch: "クウェート",
      iso3Code: "KWT",
    ),
//  Country(
//    continents: [""], isoCode: "KY",
//    phoneCode: "1-345",
//    name: "Cayman Islands",
//    nameForJpSearch: "ケイマン諸島",
//    iso3Code: "CYM",
//  ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory, L10n.of(context).europeForSearchCategory], isoCode: "KZ",
      phoneCode: "7",
      name: L10n.of(context).kazakhstanInCountryCategory,
      nameForJpSearch: "カザフスタン",
      iso3Code: "KAZ",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "LA",
      phoneCode: "",
      name: L10n.of(context).laoInCountryCategory,
      nameForJpSearch: "ラオスジンミンミンシュキョウワコク",
      iso3Code: "LAO",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "LB",
      phoneCode: "961",
      name: L10n.of(context).lebanonInCountryCategory,
      nameForJpSearch: "レバノン",
      iso3Code: "LBN",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "LC",
      phoneCode: "1-758",
      name: L10n.of(context).lcaInCountryCategory,
      nameForJpSearch: "セントルシア",
      iso3Code: "LCA",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "LI",
      phoneCode: "423",
      name: L10n.of(context).liechtensteinInCountryCategory,
      nameForJpSearch: "リヒテンシュタイン",
      iso3Code: "LIE",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "LK",
      phoneCode: "94",
      name: L10n.of(context).lkaInCountryCategory,
      nameForJpSearch: "スリランカ",
      iso3Code: "LKA",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "LR",
      phoneCode: "231",
      name: L10n.of(context).liberiaInCountryCategory,
      nameForJpSearch: "リベリア",
      iso3Code: "LBR",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "LS",
      phoneCode: "266",
      name: L10n.of(context).lesothoInCountryCategory,
      nameForJpSearch: "レソト",
      iso3Code: "LSO",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "LT",
      phoneCode: "370",
      name: L10n.of(context).lithuaniaInCountryCategory,
      nameForJpSearch: "リトアニア",
      iso3Code: "LTU",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "LU",
      phoneCode: "352",
      name: L10n.of(context).luxembourgInCountryCategory,
      nameForJpSearch: "ルクセンブルク",
      iso3Code: "LUX",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "LV",
      phoneCode: "371",
      name: L10n.of(context).latviaInCountryCategory,
      nameForJpSearch: "ラトビア",
      iso3Code: "LVA",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "LY",
      phoneCode: "218",
      name: L10n.of(context).libyaInCountryCategory,
      nameForJpSearch: "リビア",
      iso3Code: "LBY",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "MA",
      phoneCode: "212",
      name: L10n.of(context).moroccoInCountryCategory,
      nameForJpSearch: "モロッコ",
      iso3Code: "MAR",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "MC",
      phoneCode: "377",
      name: L10n.of(context).monacoInCountryCategory,
      nameForJpSearch: "モナココウコク",
      iso3Code: "MCO",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "MD",
      phoneCode: "373",
      name: L10n.of(context).mdaInCountryCategory,
//    nameForJpSearch: "モルドバ共和国",
      nameForJpSearch: "モルドバ",
      iso3Code: "MDA",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "ME",
      phoneCode: "382",
      name: L10n.of(context).montenegroInCountryCategory,
      nameForJpSearch: "モンテネグロ",
      iso3Code: "MNE",
    ),
//  Country(
//    continents: [""], isoCode: "MF",
//    phoneCode: "590",
//    name: "Saint Martin",
//    nameForJpSearch: "サン・マルタン（フランス領）",
//    iso3Code: "MAF",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "MG",
      phoneCode: "261",
      name: L10n.of(context).madagascarInCountryCategory,
      nameForJpSearch: "マダガスカル",
      iso3Code: "MDG",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory],
      isoCode: "MH",
      phoneCode: "692",
      name: L10n.of(context).mhlInCountryCategory,
      nameForJpSearch: "マーシャルショトウ",
      iso3Code: "MHL",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "MK",
      phoneCode: "389",
      name: L10n.of(context).mkdInCountryCategory,
      nameForJpSearch: "北マケドニア",
      iso3Code: "MKD",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "ML",
      phoneCode: "223",
      name: L10n.of(context).maliInCountryCategory,
      nameForJpSearch: "マリ",
      iso3Code: "MLI",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "MM",
      phoneCode: "95",
      name: L10n.of(context).myanmarInCountryCategory,
      nameForJpSearch: "ミャンマー",
      iso3Code: "MMR",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "MN",
      phoneCode: "976",
      name: L10n.of(context).mongoliaInCountryCategory,
      nameForJpSearch: "モンゴル",
      iso3Code: "MNG",
    ),
//  Country(
//    continents: [""], isoCode: "MO",
//    phoneCode: "853",
//    name: "Macao",
//    nameForJpSearch: "マカオ(中国特別行政区)",
//    iso3Code: "MAC",
//  ),
//  Country(
//    continents: [""], isoCode: "MP",
//    phoneCode: "1-670",
//    name: "Northern Mariana Islands",
//    nameForJpSearch: "北マリアナ諸島",
//    iso3Code: "MNP",
//  ),
//  Country(
//    continents: [""], isoCode: "MQ",
//    phoneCode: "596",
//    name: "Martinique",
//    nameForJpSearch: "マルティニーク",
//    iso3Code: "MTQ",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "MR",
      phoneCode: "222",
      name: L10n.of(context).mauritaniaInCountryCategory,
      nameForJpSearch: "モーリタニア",
      iso3Code: "MRT",
    ),
//  Country(
//    continents: [""], isoCode: "MS",
//    phoneCode: "1-664",
//    name: "Montserrat",
//    nameForJpSearch: "モントセラト",
//    iso3Code: "MSR",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "MT",
      phoneCode: "356",
      name: L10n.of(context).maltaInCountryCategory,
      nameForJpSearch: "マルタ",
      iso3Code: "MLT",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "MU",
      phoneCode: "230",
      name: L10n.of(context).mauritiusInCountryCategory,
      nameForJpSearch: "モーリシャス",
      iso3Code: "MUS",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "MV",
      phoneCode: "960",
      name: L10n.of(context).maldivesInCountryCategory,
      nameForJpSearch: "モルディブ",
      iso3Code: "MDV",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "MW",
      phoneCode: "265",
      name: L10n.of(context).malawiInCountryCategory,
      nameForJpSearch: "マラウイ",
      iso3Code: "MWI",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "MX",
      phoneCode: "52",
      name: L10n.of(context).mexicoInCountryCategory,
      nameForJpSearch: "メキシコ",
      iso3Code: "MEX",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "MY",
      phoneCode: "60",
      name: L10n.of(context).malaysiaInCountryCategory,
      nameForJpSearch: "マレーシア",
      iso3Code: "MYS",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "MZ",
      phoneCode: "258",
      name: L10n.of(context).mozambiqueInCountryCategory,
      nameForJpSearch: "モザンビーク",
      iso3Code: "MOZ",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "NA",
      phoneCode: "264",
      name: L10n.of(context).namibiaInCountryCategory,
      nameForJpSearch: "ナミビア",
      iso3Code: "NAM",
    ),
//  Country(
//    continents: [""], isoCode: "NC",
//    phoneCode: "687",
//    name: "New Caledonia",
//    nameForJpSearch: "ニューカレドニア",
//    iso3Code: "NCL",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "NE",
      phoneCode: "227",
      name: L10n.of(context).nigerInCountryCategory,
      nameForJpSearch: "ニジェール",
      iso3Code: "NER",
    ),
//  Country(
//    continents: [""], isoCode: "NF",
//    phoneCode: "672",
//    name: "Norfolk Island",
//    nameForJpSearch: "ノーフォーク島",
//    iso3Code: "NFK",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "NG",
      phoneCode: "234",
      name: L10n.of(context).nigeriaInCountryCategory,
      nameForJpSearch: "ナイジェリア",
      iso3Code: "NGA",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "NI",
      phoneCode: "505",
      name: L10n.of(context).nicaraguaInCountryCategory,
      nameForJpSearch: "ニカラグア",
      iso3Code: "NIC",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "NL",
      phoneCode: "31",
      name: L10n.of(context).netherlandsInCountryCategory,
      nameForJpSearch: "オランダ",
      iso3Code: "NLD",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "NO",
      phoneCode: "47",
      name: L10n.of(context).norwayInCountryCategory,
      nameForJpSearch: "ノルウェー",
      iso3Code: "NOR",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "NP",
      phoneCode: "977",
      name: L10n.of(context).nepalInCountryCategory,
      nameForJpSearch: "ネパール",
      iso3Code: "NPL",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory],
      isoCode: "NR",
      phoneCode: "674",
      name: L10n.of(context).nauruInCountryCategory,
//    nameForJpSearch: "ナウル共和国",
      nameForJpSearch: "ナウル",
      iso3Code: "NRU",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory],
      isoCode: "NU",
      phoneCode: "683",
      name: L10n.of(context).niueInCountryCategory,
      nameForJpSearch: "ニウエ",
      iso3Code: "NIU",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "NZ",
      phoneCode: "64",
      name: L10n.of(context).nzlInCountryCategory,
      nameForJpSearch: "ニュージーランド",
      iso3Code: "NZL",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "OM",
      phoneCode: "968",
      name: L10n.of(context).omanInCountryCategory,
      nameForJpSearch: "オマーン",
      iso3Code: "OMN",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "PA",
      phoneCode: "507",
      name: L10n.of(context).panamaInCountryCategory,
      nameForJpSearch: "パナマ",
      iso3Code: "PAN",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "PE",
      phoneCode: "51",
      name: L10n.of(context).peruInCountryCategory,
      nameForJpSearch: "ペルー",
      iso3Code: "PER",
    ),
//  Country(
//    continents: [""], isoCode: "PF",
//    phoneCode: "689",
//    name: "French Polynesia",
//    nameForJpSearch: "フランス領ポリネシア",
//    iso3Code: "PYF",
//  ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "PG",
      phoneCode: "675",
      name: L10n.of(context).pngInCountryCategory,
      nameForJpSearch: "パプア・ニューギニア",
      iso3Code: "PNG",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "PH",
      phoneCode: "63",
      name: L10n.of(context).philippinesInCountryCategory,
      nameForJpSearch: "フィリピン",
      iso3Code: "PHL",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "PK",
      phoneCode: "92",
      name: L10n.of(context).pakistanInCountryCategory,
      nameForJpSearch: "パキスタン",
      iso3Code: "PAK",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "PL",
      phoneCode: "48",
      name: L10n.of(context).polandInCountryCategory,
      nameForJpSearch: "ポーランド",
      iso3Code: "POL",
    ),
//  Country(
//    continents: [L10n.of(context).oceaniaForSearchCategory],
//    isoCode: "PM",
//    phoneCode: "508",
//    name: "Saint Pierre and Miquelon",
//    nameForJpSearch: "サンピエール島・ミクロン島",
//    iso3Code: "SPM",
//  ),
//  Country(
//    continents: [""], isoCode: "PN",
//    phoneCode: "64",
//    name: "Pitcairn",
//    nameForJpSearch: "ピトケアン",
//    iso3Code: "PCN",
//  ),
//  Country(
//    continents: [""], isoCode: "PR",
//    phoneCode: "1-787",
//    name: "Puerto Rico",
//    nameForJpSearch: "プエルトリコ",
//    iso3Code: "PRI",
//  ),
//  Country(
//    continents: [""], isoCode: "PS",
//    phoneCode: "970",
//    name: "Palestine",
//    nameForJpSearch: "パレスチナ",
//    iso3Code: "PSE",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "PT",
      phoneCode: "351",
      name: L10n.of(context).portugalInCountryCategory,
      nameForJpSearch: "ポルトガル",
      iso3Code: "PRT",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "PW",
      phoneCode: "680",
      name: L10n.of(context).palauInCountryCategory,
      nameForJpSearch: "パラオ",
      iso3Code: "PLW",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "PY",
      phoneCode: "595",
      name: L10n.of(context).paraguayInCountryCategory,
      nameForJpSearch: "パラグアイ",
      iso3Code: "PRY",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "QA",
      phoneCode: "974",
      name: L10n.of(context).qatarInCountryCategory,
      nameForJpSearch: "カタール",
      iso3Code: "QAT",
    ),
//  Country(
//    continents: [""], isoCode: "RE",
//    phoneCode: "262",
//    name: "Réunion",
//    nameForJpSearch: "レユニオン",
//    iso3Code: "REU",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "RO",
      phoneCode: "40",
      name: L10n.of(context).romaniaInCountryCategory,
      nameForJpSearch: "ルーマニア",
      iso3Code: "ROU",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "RS",
      phoneCode: "381",
      name: L10n.of(context).serbiaInCountryCategory,
      nameForJpSearch: "セルビア",
      iso3Code: "SRB",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory, L10n.of(context).europeForSearchCategory], isoCode: "RU",
      phoneCode: "7",
      name: L10n.of(context).rusInCountryCategory,
//    nameForJpSearch: "ロシア連邦",
      nameForJpSearch: "ロシア",
      iso3Code: "RUS",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "RW",
      phoneCode: "250",
      name: L10n.of(context).rwandaInCountryCategory,
      nameForJpSearch: "ルワンダ",
      iso3Code: "RWA",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "SA",
      phoneCode: "966",
      name: L10n.of(context).sauInCountryCategory,
      nameForJpSearch: "サウジアラビア",
      iso3Code: "SAU",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "SB",
      phoneCode: "677",
      name: L10n.of(context).slbInCountryCategory,
      nameForJpSearch: "ソロモンショトウ",
      iso3Code: "SLB",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "SC",
      phoneCode: "248",
      name: L10n.of(context).seychellesInCountryCategory,
      nameForJpSearch: "セーシェル",
      iso3Code: "SYC",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "SD",
      phoneCode: "249",
      name: L10n.of(context).sudanInCountryCategory,
      nameForJpSearch: "スーダン",
      iso3Code: "SDN",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "SE",
      phoneCode: "46",
      name: L10n.of(context).swedenInCountryCategory,
      nameForJpSearch: "スウェーデン",
      iso3Code: "SWE",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "SG",
      phoneCode: "65",
      name: L10n.of(context).singaporeInCountryCategory,
      nameForJpSearch: "シンガポール",
      iso3Code: "SGP",
    ),
    // Country(
    //   continents: [""], isoCode: "SH",
    //   phoneCode: "290",
    //   name: "Saint Helena, Ascension and Tristan da Cunha",
    //   nameForJpSearch: "セントヘレナ・アセンションおよびトリスタンダクーニャ",
    //   iso3Code: "SHN",
    // ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "SI",
      phoneCode: "386",
      name: L10n.of(context).sloveniaInCountryCategory,
      nameForJpSearch: "スロベニア",
      iso3Code: "SVN",
    ),
//  Country(
//    continents: [""], isoCode: "SJ",
//    phoneCode: "47",
//    name: "Svalbard and Jan Mayen Islands",
//    nameForJpSearch: "スヴァールバル諸島およびヤンマイエン島",
//    iso3Code: "SJM",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "SK",
      phoneCode: "421",
      name: L10n.of(context).slovakiaInCountryCategory,
      nameForJpSearch: "スロバキア",
      iso3Code: "SVK",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "SL",
      phoneCode: "232",
      name: L10n.of(context).sleInCountryCategory,
      nameForJpSearch: "シエラレオネ",
      iso3Code: "SLE",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "SM",
      phoneCode: "378",
      name: L10n.of(context).smrInCountryCategory,
      nameForJpSearch: "サンマリノ",
      iso3Code: "SMR",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "SN",
      phoneCode: "221",
      name: L10n.of(context).senegalInCountryCategory,
      nameForJpSearch: "セネガル",
      iso3Code: "SEN",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "SO",
      phoneCode: "252",
      name: L10n.of(context).somaliaInCountryCategory,
      nameForJpSearch: "ソマリア",
      iso3Code: "SOM",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "SR",
      phoneCode: "597",
      name: L10n.of(context).surinameInCountryCategory,
      nameForJpSearch: "スリナム",
      iso3Code: "SUR",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "SS",
      phoneCode: "211",
      name: L10n.of(context).ssdInCountryCategory,
      nameForJpSearch: "ミナミスーダン",
      iso3Code: "SSD",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "ST",
      phoneCode: "239",
      name: L10n.of(context).stpInCountryCategory,
      nameForJpSearch: "サントメ・プリンシペ",
      iso3Code: "STP",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "SV",
      phoneCode: "503",
      name: L10n.of(context).slvInCountryCategory,
      nameForJpSearch: "エルサルバドル",
      iso3Code: "SLV",
    ),
//  Country(
//    continents: [""], isoCode: "SX",
//    phoneCode: "1-721",
//    name: "Sint Maarten (Dutch part)",
//    nameForJpSearch: "シント・マールテン",
//    iso3Code: "SXM",
//  ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "SY",
      phoneCode: "963",
      name: L10n.of(context).syrInCountryCategory,
//    nameForJpSearch: "シリア・アラブ共和国",
      nameForJpSearch: "シリア",
      iso3Code: "SYR",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "SZ",
      phoneCode: "268",
      name: L10n.of(context).swzInCountryCategory,
      nameForJpSearch: "エスワティニ",
      iso3Code: "SWZ",
    ),
//  Country(
//    continents: [""], isoCode: "TC",
//    phoneCode: "1-649",
//    name: "Turks and Caicos Islands",
//    nameForJpSearch: "タークス・カイコス諸島",
//    iso3Code: "TCA",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "TD",
      phoneCode: "235",
      name: L10n.of(context).chadInCountryCategory,
      nameForJpSearch: "チャド",
      iso3Code: "TCD",
    ),
//  Country(
//    continents: [""], isoCode: "TF",
//    phoneCode: "262",
//    name: "French Southern Territories",
//    nameForJpSearch: "フランス領南方・南極地域",
//    iso3Code: "ATF",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "TG",
      phoneCode: "228",
      name: L10n.of(context).togoInCountryCategory,
      nameForJpSearch: "トーゴ",
      iso3Code: "TGO",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "TH",
      phoneCode: "66",
      name: L10n.of(context).thailandInCountryCategory,
      nameForJpSearch: "タイ",
      iso3Code: "THA",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "TJ",
      phoneCode: "992",
      name: L10n.of(context).tajikistanInCountryCategory,
      nameForJpSearch: "タジキスタン",
      iso3Code: "TJK",
    ),
//  Country(
//    continents: [""], isoCode: "TK",
//    phoneCode: "690",
//    name: "Tokelau",
//    nameForJpSearch: "トケラウ",
//    iso3Code: "TKL",
//  ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "TL",
      phoneCode: "670",
      name: L10n.of(context).tlsInCountryCategory,
      nameForJpSearch: "ヒガシティモール",
      iso3Code: "TLS",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "TM",
      phoneCode: "993",
      name: L10n.of(context).turkmenistanInCountryCategory,
      nameForJpSearch: "トルクメニスタン",
      iso3Code: "TKM",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "TN",
      phoneCode: "216",
      name: L10n.of(context).tunisiaInCountryCategory,
      nameForJpSearch: "チュニジア",
      iso3Code: "TUN",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "TO",
      phoneCode: "676",
      name: L10n.of(context).tongaInCountryCategory,
      nameForJpSearch: "トンガ",
      iso3Code: "TON",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory, L10n.of(context).europeForSearchCategory], isoCode: "TR",
      phoneCode: "90",
      name: L10n.of(context).turkeyInCountryCategory,
      nameForJpSearch: "トルコ",
      iso3Code: "TUR",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "TT",
      phoneCode: "1-868",
      name: L10n.of(context).ttoInCountryCategory,
      nameForJpSearch: "トリニダード・トバゴ",
      iso3Code: "TTO",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "TV",
      phoneCode: "688",
      name: L10n.of(context).tuvaluInCountryCategory,
      nameForJpSearch: "ツバル",
      iso3Code: "TUV",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory],
      isoCode: "TW",
      phoneCode: "886",
      name: L10n.of(context).taiwanInCountryCategory,
      nameForJpSearch: "タイワン",
      iso3Code: "TWN",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "TZ",
      phoneCode: "255",
      name: L10n.of(context).tzaInCountryCategory,
      nameForJpSearch: "タンザニア",
      iso3Code: "TZA",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "UA",
      phoneCode: "380",
      name: L10n.of(context).ukrInCountryCategory,
      nameForJpSearch: "ウクライナ",
      iso3Code: "UKR",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "UG",
      phoneCode: "256",
      name: L10n.of(context).ugaInCountryCategory,
      nameForJpSearch: "ウガンダ",
      iso3Code: "UGA",
    ),
//  Country(
//    continents: [""], isoCode: "UM",
//    phoneCode: "1",
//    name: "US Minor Outlying Islands",
//    nameForJpSearch: "合衆国領有小離島",
//    iso3Code: "UMI",
//  ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "US",
      phoneCode: "1",
      name: L10n.of(context).usaInCountryCategory,
      nameForJpSearch: "アメリカガッシュウコク",
      iso3Code: "USA",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "UY",
      phoneCode: "598",
      name: L10n.of(context).uruguayInCountryCategory,
      nameForJpSearch: "ウルグアイ",
      iso3Code: "URY",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "UZ",
      phoneCode: "998",
      name: L10n.of(context).uzbekistanInCountryCategory,
      nameForJpSearch: "ウズベキスタン",
      iso3Code: "UZB",
    ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "VA",
      phoneCode: "379",
      name: L10n.of(context).vatInCountryCategory,
      nameForJpSearch: "バチカンシコク",
      iso3Code: "VAT",
    ),
    Country(
      continents: [L10n.of(context).northAmericaForSearchCategory], isoCode: "VC",
      phoneCode: "1-784",
      name: L10n.of(context).vctInCountryCategory,
      nameForJpSearch: "セントビンセントおよびグレナディーンショトウ",
      iso3Code: "VCT",
    ),
    Country(
      continents: [L10n.of(context).southAmericaForSearchCategory], isoCode: "VE",
      phoneCode: "58",
      name: L10n.of(context).venInCountryCategory,
//    nameForJpSearch: "ベネズエラ・ボリバル共和国",
      nameForJpSearch: "ベネズエラ",
      iso3Code: "VEN",
    ),
//  Country(
//    continents: [""], isoCode: "VG",
//    phoneCode: "1-284",
//    name: "Virgin Islands, British",
//    nameForJpSearch: "イギリス領ヴァージン諸島",
//    iso3Code: "VGB",
//  ),
//  Country(
//    continents: [""], isoCode: "VI",
//    phoneCode: "1-340",
//    name: "Virgin Islands, U.S.",
//    nameForJpSearch: "アメリカ領ヴァージン諸島",
//    iso3Code: "VIR",
//  ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "VN",
      phoneCode: "84",
      name: L10n.of(context).vietnamInCountryCategory,
      nameForJpSearch: "ベトナム",
      iso3Code: "VNM",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "VU",
      phoneCode: "678",
      name: L10n.of(context).vanuatuInCountryCategory,
      nameForJpSearch: "バヌアツ",
      iso3Code: "VUT",
    ),
//  Country(
//    continents: [""], isoCode: "WF",
//    phoneCode: "681",
//    name: "Wallis and Futuna Islands",
//    nameForJpSearch: "ウォリス・フツナ",
//    iso3Code: "WLF",
//  ),
    Country(
      continents: [L10n.of(context).europeForSearchCategory], isoCode: "XK",
      phoneCode: "383",
      name: L10n.of(context).kosovoInCountryCategory,
      nameForJpSearch: "コソボ",
      iso3Code: "KOS",
    ),
    Country(
      continents: [L10n.of(context).oceaniaForSearchCategory], isoCode: "WS",
      phoneCode: "685",
      name: L10n.of(context).samoaInCountryCategory,
      nameForJpSearch: "サモア",
      iso3Code: "WSM",
    ),
    Country(
      continents: [L10n.of(context).asiaForSearchCategory], isoCode: "YE",
      phoneCode: "967",
      name: L10n.of(context).yemenInCountryCategory,
      nameForJpSearch: "イエメン",
      iso3Code: "YEM",
    ),
//  Country(
//    continents: [""], isoCode: "YT",
//    phoneCode: "262",
//    name: "Mayotte",
//    nameForJpSearch: "マヨット",
//    iso3Code: "MYT",
//  ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "ZA",
      phoneCode: "27",
      name: L10n.of(context).zafInCountryCategory,
      nameForJpSearch: "ミナミアフリカ",
      iso3Code: "ZAF",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "ZM",
      phoneCode: "260",
      name: L10n.of(context).zambiaInCountryCategory,
      nameForJpSearch: "ザンビア",
      iso3Code: "ZMB",
    ),
    Country(
      continents: [L10n.of(context).africaForSearchCategory], isoCode: "ZW",
      phoneCode: "263",
      name: L10n.of(context).zimbabweInCountryCategory,
      nameForJpSearch: "ジンバブエ",
      iso3Code: "ZWE",
    ),
  ];
}


