import 'package:country_quiz/fix_pub_lib/country_pickers_1.1.0_fix/country.dart';

final List<Country> countryList = [
  Country(
    continents: [""],
    isoCode: "AD",
    phoneCode: "376",
    name: "Andorra",
    jpName: "アンドラ",
    iso3Code: "AND",
  ),
  Country(
    continents: [""], isoCode: "AE",
    phoneCode: "971",
    name: "United Arab Emirates",
    jpName: "アラブ首長国連邦",
    iso3Code: "ARE",
  ),
  Country(
    continents: [""], isoCode: "AF",
    phoneCode: "93",
    name: "Afghanistan",
    jpName: "アフガニスタン",
    iso3Code: "AFG",
  ),
  Country(
    continents: [""], isoCode: "AG",
    phoneCode: "1-268",
    name: "Antigua and Barbuda",
    jpName: "アンティグア・バーブーダ",
    iso3Code: "ATG",
  ),
  Country(
    continents: [""], isoCode: "AI",
    phoneCode: "1-264",
    name: "Anguilla",
    jpName: "アンギラ",
    iso3Code: "AIA",
  ),
  Country(
    continents: [""], isoCode: "AL",
    phoneCode: "355",
    name: "Albania",
    jpName: "アルバニア",
    iso3Code: "ALB",
  ),
  Country(
    continents: [""], isoCode: "AM",
    phoneCode: "374",
    name: "Armenia",
    jpName: "アルメニア",
    iso3Code: "ARM",
  ),
//  Country(
//    continents: [""], isoCode: "AN",
//    phoneCode: "599",
//    name: "Netherlands Antilles",
//    jpName: "",
//    iso3Code: "AN",
//  ),
  Country(
    continents: [""], isoCode: "AO",
    phoneCode: "244",
    name: "Angola",
    jpName: "アンゴラ",
    iso3Code: "AGO",
  ),
//  Country(
//    continents: [""], isoCode: "AQ",
//    phoneCode: "672",
//    name: "Antarctica",
//    jpName: "南極",
//    iso3Code: "ATA",
//  ),
  Country(
    continents: [""], isoCode: "AR",
    phoneCode: "54",
    name: "Argentina",
    jpName: "アルゼンチン",
    iso3Code: "ARG",
  ),
  Country(
    continents: [""], isoCode: "AS",
    phoneCode: "1-684",
    name: "American Samoa",
    jpName: "アメリカ領サモア",
    iso3Code: "ASM",
  ),
  Country(
    continents: [""], isoCode: "AT",
    phoneCode: "43",
    name: "Austria",
    jpName: "オーストリア",
    iso3Code: "AUT",
  ),
  Country(
    continents: [""], isoCode: "AU",
    phoneCode: "61",
    name: "Australia",
    jpName: "オーストラリア",
    iso3Code: "AUS",
  ),
  Country(
    continents: [""], isoCode: "AW",
    phoneCode: "297",
    name: "Aruba",
    jpName: "アルバ",
    iso3Code: "ABW",
  ),
  Country(
    continents: [""], isoCode: "AX",
    phoneCode: "358",
    name: "Åland Islands",
    jpName: "オーランド諸島",
    iso3Code: "ALA",
  ),
  Country(
    continents: [""], isoCode: "AZ",
    phoneCode: "994",
    name: "Azerbaijan",
    jpName: "アゼルバイジャン",
    iso3Code: "AZE",
  ),
  Country(
    continents: [""], isoCode: "BA",
    phoneCode: "387",
    name: "Bosnia and Herzegovina",
    jpName: "ボスニアヘルツェゴビナ",
    iso3Code: "BIH",
  ),
  Country(
    continents: [""], isoCode: "BB",
    phoneCode: "1-246",
    name: "Barbados",
    jpName: "バルバドス",
    iso3Code: "BRB",
  ),
  Country(
    continents: [""], isoCode: "BD",
    phoneCode: "880",
    name: "Bangladesh",
    jpName: "バングラデシュ",
    iso3Code: "BGD",
  ),
  Country(
    continents: [""], isoCode: "BE",
    phoneCode: "32",
    name: "Belgium",
    jpName: "ベルギー",
    iso3Code: "BEL",
  ),
  Country(
    continents: [""], isoCode: "BF",
    phoneCode: "226",
    name: "Burkina Faso",
    jpName:"ブルキナファソ ",
    iso3Code: "BFA",
  ),
  Country(
    continents: [""], isoCode: "BG",
    phoneCode: "359",
    name: "Bulgaria",
    jpName: "ブルガリア",
    iso3Code: "BGR",
  ),
  Country(
    continents: [""], isoCode: "BH",
    phoneCode: "973",
    name: "Bahrain",
    jpName: "バーレーン",
    iso3Code: "BHR",
  ),
  Country(
    continents: [""], isoCode: "BI",
    phoneCode: "257",
    name: "Burundi",
    jpName: "ブルンジ",
    iso3Code: "BDI",
  ),
  Country(
    continents: [""], isoCode: "BJ",
    phoneCode: "229",
    name: "Benin",
    jpName: "ベナン",
    iso3Code: "BEN",
  ),
  Country(
    continents: [""], isoCode: "BL",
    phoneCode: "590",
    name: "Saint Barthélemy",
    jpName: "サン・バルテルミー",
    iso3Code: "BLM",
  ),
  Country(
    continents: [""], isoCode: "BM",
    phoneCode: "1-441",
    name: "Bermuda",
    jpName: "バミューダ",
    iso3Code: "BMU",
  ),
  Country(
    continents: [""], isoCode: "BN",
    phoneCode: "673",
    name: "Brunei Darussalam",
    jpName: "ブルネイダルサラーム",
    iso3Code: "BRN",
  ),
  Country(
    continents: [""], isoCode: "BO",
    phoneCode: "591",
    name: "Bolivia, Plurinational State of",
    jpName: "ボリビア多民族国家",
    iso3Code: "BOL",
  ),
  Country(
    continents: [""], isoCode: "BQ",
    phoneCode: "599",
    name: "Caribbean Netherlands",
    jpName: "カリブ・オランダ",
    iso3Code: "BES",
  ),
  Country(
    continents: [""], isoCode: "BR",
    phoneCode: "55",
    name: "Brazil",
    jpName: "ブラジル",
    iso3Code: "BRA",
  ),
  Country(
    continents: [""], isoCode: "BS",
    phoneCode: "1-242",
    name: "Bahamas",
    jpName: "バハマ",
    iso3Code: "BHS",
  ),
  Country(
    continents: [""], isoCode: "BT",
    phoneCode: "975",
    name: "Bhutan",
    jpName: "ブータン王国",
    iso3Code: "BTN",
  ),
  Country(
    continents: [""], isoCode: "BV",
    phoneCode: "47",
    name: "Bouvet Island",
    jpName: "ブーベ島",
    iso3Code: "BVT",
  ),
  Country(
    continents: [""], isoCode: "BW",
    phoneCode: "267",
    name: "Botswana",
    jpName: "ボツワナ",
    iso3Code: "BWA",
  ),
  Country(
    continents: [""], isoCode: "BY",
    phoneCode: "375",
    name: "Belarus",
    jpName: "ベラルーシ",
    iso3Code: "BLR",
  ),
  Country(
    continents: [""], isoCode: "BZ",
    phoneCode: "501",
    name: "Belize",
    jpName: "ベリーズ",
    iso3Code: "BLZ",
  ),
  Country(
    continents: [""], isoCode: "CA",
    phoneCode: "1",
    name: "Canada",
    jpName: "カナダ",
    iso3Code: "CAN",
  ),
  Country(
    continents: [""], isoCode: "CC",
    phoneCode: "61",
    name: "Cocos (Keeling) Islands",
    jpName: "ココス諸島",
    iso3Code: "CCK",
  ),
  Country(
    continents: [""], isoCode: "CD",
    phoneCode: "243",
    name: "Congo, the Democratic Republic of the",
    jpName: "コンゴ民主共和国",
    iso3Code: "COD",
  ),
  Country(
    continents: [""], isoCode: "CF",
    phoneCode: "236",
    name: "Central African Republic",
    jpName: "中央アフリカ共和国",
    iso3Code: "CAF",
  ),
  Country(
    continents: [""], isoCode: "CG",
    phoneCode: "242",
    name: "Congo",
    jpName: "コンゴ共和国",
    iso3Code: "COG",
  ),
  Country(
    continents: [""], isoCode: "CH",
    phoneCode: "41",
    name: "Switzerland",
    jpName: "スイス",
    iso3Code: "CHE",
  ),
  Country(
    continents: [""], isoCode: "CI",
    phoneCode: "225",
    name: "Côte d'Ivoire",
    jpName: "コートジボワール",
    iso3Code: "CIV",
  ),
  Country(
    continents: [""], isoCode: "CK",
    phoneCode: "682",
    name: "Cook Islands",
    jpName: "クック諸島",
    iso3Code: "COK",
  ),
  Country(
    continents: [""], isoCode: "CL",
    phoneCode: "56",
    name: "Chile",
    jpName: "チリ",
    iso3Code: "CHL",
  ),
  Country(
    continents: [""], isoCode: "CM",
    phoneCode: "237",
    name: "Cameroon",
    jpName: "カメルーン",
    iso3Code: "CMR",
  ),
  Country(
    continents: [""], isoCode: "CN",
    phoneCode: "86",
    name: "China",
    jpName: "中国",
    iso3Code: "CHN",
  ),
  Country(
    continents: [""], isoCode: "CO",
    phoneCode: "57",
    name: "Colombia",
    jpName: "コロンビア",
    iso3Code: "COL",
  ),
  Country(
    continents: [""], isoCode: "CR",
    phoneCode: "506",
    name: "Costa Rica",
    jpName: "コスタリカ",
    iso3Code: "CRI",
  ),
  Country(
    continents: [""], isoCode: "CU",
    phoneCode: "53",
    name: "Cuba",
    jpName: "キューバ",
    iso3Code: "CUB",
  ),
  Country(
    continents: [""], isoCode: "CV",
    phoneCode: "238",
    name: "Cape Verde",
    jpName: "カーボベルデ",
    iso3Code: "CPV",
  ),
  Country(
    continents: [""], isoCode: "CW",
    phoneCode: "599",
    name: "Curaçao",
    jpName: "キュラソー",
    iso3Code: "CUW",
  ),
  Country(
    continents: [""], isoCode: "CX",
    phoneCode: "61",
    name: "Christmas Island",
    jpName: "クリスマス島",
    iso3Code: "CXR",
  ),
  Country(
    continents: [""], isoCode: "CY",
    phoneCode: "357",
    name: "Cyprus",
    jpName: "キプロス",
    iso3Code: "CYP",
  ),
  Country(
    continents: [""], isoCode: "CZ",
    phoneCode: "420",
    name: "Czech Republic",
    jpName: "チェコ共和国",
    iso3Code: "CZE",
  ),
  Country(
    continents: [""], isoCode: "DE",
    phoneCode: "49",
    name: "Germany",
    jpName: "ドイツ",
    iso3Code: "DEU",
  ),
  Country(
    continents: [""], isoCode: "DJ",
    phoneCode: "253",
    name: "Djibouti",
    jpName: "ジブチ",
    iso3Code: "DJI",
  ),
  Country(
    continents: [""], isoCode: "DK",
    phoneCode: "45",
    name: "Denmark",
    jpName: "デンマーク",
    iso3Code: "DNK",
  ),
  Country(
    continents: [""], isoCode: "DM",
    phoneCode: "1-767",
    name: "Dominica",
    jpName: "ドミニカ国",
    iso3Code: "DMA",
  ),
  Country(
    continents: [""], isoCode: "DO",
    phoneCode: "1-849",
    name: "Dominican Republic",
    jpName: "ドミニカ共和国",
    iso3Code: "DOM",
  ),
  Country(
    continents: [""], isoCode: "DZ",
    phoneCode: "213",
    name: "Algeria",
    jpName: "アルジェリア",
    iso3Code: "DZA",
  ),
  Country(
    continents: [""], isoCode: "EC",
    phoneCode: "593",
    name: "Ecuador",
    jpName: "エクアドル",
    iso3Code: "ECU",
  ),
  Country(
    continents: [""], isoCode: "EE",
    phoneCode: "372",
    name: "Estonia",
    jpName: "エストニア",
    iso3Code: "EST",
  ),
  Country(
    continents: [""], isoCode: "EG",
    phoneCode: "20",
    name: "Egypt",
    jpName: "エジプト",
    iso3Code: "EGY",
  ),
  Country(
    continents: [""], isoCode: "EH",
    phoneCode: "212",
    name: "Western Sahara",
    jpName: "西サハラ",
    iso3Code: "ESH",
  ),
  Country(
    continents: [""], isoCode: "ER",
    phoneCode: "291",
    name: "Eritrea",
    jpName: "エリトリア",
    iso3Code: "ERI",
  ),
  Country(
    continents: [""], isoCode: "ES",
    phoneCode: "34",
    name: "Spain",
    jpName: "スペイン",
    iso3Code: "ESP",
  ),
  Country(
    continents: [""], isoCode: "ET",
    phoneCode: "251",
    name: "Ethiopia",
    jpName: "エチオピア",
    iso3Code: "ETH",
  ),
  Country(
    continents: [""], isoCode: "FI",
    phoneCode: "358",
    name: "Finland",
    jpName: "フィンランド",
    iso3Code: "FIN",
  ),
  Country(
    continents: [""], isoCode: "FJ",
    phoneCode: "679",
    name: "Fiji",
    jpName: "フィジー",
    iso3Code: "FJI",
  ),
  Country(
    continents: [""], isoCode: "FK",
    phoneCode: "500",
    name: "Falkland Islands (Malvinas)",
    jpName: "フォークランド諸島",
    iso3Code: "FLK",
  ),
  Country(
    continents: [""], isoCode: "FM",
    phoneCode: "691",
    name: "Micronesia, Federated States of",
    jpName: "ミクロネシア連邦",
    iso3Code: "FSM",
  ),
  Country(
    continents: [""], isoCode: "FO",
    phoneCode: "298",
    name: "Faroe Islands",
    jpName: "フェロー諸島",
    iso3Code: "FRO",
  ),
  Country(
    continents: [""], isoCode: "FR",
    phoneCode: "33",
    name: "France",
    jpName: "フランス",
    iso3Code: "FRA",
  ),
  Country(
    continents: [""], isoCode: "GA",
    phoneCode: "241",
    name: "Gabon",
    jpName: "ガボン",
    iso3Code: "GAB",
  ),
  Country(
    continents: [""], isoCode: "GB",
    phoneCode: "44",
    name: "United Kingdom",
    jpName: "イギリス",
    iso3Code: "GBR",
  ),
  // Country(
  //   continents: [""], isoCode: "GB-ENG",
  //   phoneCode: "44",
  //   name: "England",
  //   jpName: "イングランド",
  //   iso3Code: "GBR",
  // ),
  // Country(
  //   continents: [""], isoCode: "GB-NIR",
  //   phoneCode: "44",
  //   name: "Northern Ireland",
  //   jpName: "北アイルランド",
  //   iso3Code: "GBR",
  // ),
  // Country(
  //   continents: [""], isoCode: "GB-SCT",
  //   phoneCode: "44",
  //   name: "Scotland",
  //   jpName: "スコットランド",
  //   iso3Code: "GBR",
  // ),
  // Country(
  //   continents: [""], isoCode: "GB-WLS",
  //   phoneCode: "44",
  //   name: "Wales",
  //   jpName: "ウェールズ",
  //   iso3Code: "GBR",
  // ),
  Country(
    continents: [""], isoCode: "GD",
    phoneCode: "1-473",
    name: "Grenada",
    jpName: "グレナダ",
    iso3Code: "GRD",
  ),
  Country(
    continents: [""], isoCode: "GE",
    phoneCode: "995",
    name: "Georgia",
    jpName: "ジョージア",
    iso3Code: "GEO",
  ),
  Country(
    continents: [""], isoCode: "GF",
    phoneCode: "594",
    name: "French Guiana",
    jpName: "フランス領ギアナ",
    iso3Code: "GUF",
  ),
  Country(
    continents: [""], isoCode: "GG",
    phoneCode: "44-1481",
    name: "Guernsey",
    jpName: "ガーンジー",
    iso3Code: "GGY",
  ),
  Country(
    continents: [""], isoCode: "GH",
    phoneCode: "233",
    name: "Ghana",
    jpName: "ガーナ",
    iso3Code: "GHA",
  ),
  Country(
    continents: [""], isoCode: "GI",
    phoneCode: "350",
    name: "Gibraltar",
    jpName: "ジブラルタル",
    iso3Code: "GIB",
  ),
  Country(
    continents: [""], isoCode: "GL",
    phoneCode: "299",
    name: "Greenland",
    jpName: "ジブラルタル",
    iso3Code: "GRL",
  ),
  Country(
    continents: [""], isoCode: "GM",
    phoneCode: "220",
    name: "Gambia",
    jpName: "ガンビア",
    iso3Code: "GMB",
  ),
  Country(
    continents: [""], isoCode: "GN",
    phoneCode: "224",
    name: "Guinea",
    jpName: "ギニア",
    iso3Code: "GIN",
  ),
  Country(
    continents: [""], isoCode: "GP",
    phoneCode: "590",
    name: "Guadeloupe",
    jpName: "グアドループ",
    iso3Code: "GLP",
  ),
  Country(
    continents: [""], isoCode: "GQ",
    phoneCode: "240",
    name: "Equatorial Guinea",
    jpName: "赤道ギニア",
    iso3Code: "GNQ",
  ),
  Country(
    continents: [""], isoCode: "GR",
    phoneCode: "30",
    name: "Greece",
    jpName: "ギリシャ",
    iso3Code: "GRC",
  ),
//  Country(
//    continents: [""], isoCode: "GS",
//    phoneCode: "500",
//    name: "South Georgia and the South Sandwich Islands",
//    jpName: "サウスジョージア・サウスサンドウィッチ諸島",
//    iso3Code: "SGS",
//  ),
  Country(
    continents: [""], isoCode: "GT",
    phoneCode: "502",
    name: "Guatemala",
    jpName: "グアテマラ",
    iso3Code: "GTM",
  ),
  // Country(
  //   continents: [""], isoCode: "GU",
  //   phoneCode: "1-671",
  //   name: "Guam",
  //   jpName: "グアム",
  //   iso3Code: "GUM",
  // ),
  Country(
    continents: [""], isoCode: "GW",
    phoneCode: "245",
    name: "Guinea-Bissau",
    jpName: "ギニアビサウ",
    iso3Code: "GNB",
  ),
  Country(
    continents: [""], isoCode: "GY",
    phoneCode: "592",
    name: "Guyana",
    jpName: "ガイアナ",
    iso3Code: "GUY",
  ),
  Country(
    continents: [""], isoCode: "HK",
    phoneCode: "852",
    name: "Hong Kong",
    jpName: "香港(中国特別行政区)",
    iso3Code: "HKG",
  ),
  Country(
    continents: [""], isoCode: "HM",
    phoneCode: "672",
    name: "Heard Island and McDonald Islands",
    jpName: "ハード島とマクドナルド諸島",
    iso3Code: "HMD",
  ),
  Country(
    continents: [""], isoCode: "HN",
    phoneCode: "504",
    name: "Honduras",
    jpName: "ホンジュラス",
    iso3Code: "HND",
  ),
  Country(
    continents: [""], isoCode: "HR",
    phoneCode: "385",
    name: "Croatia",
    jpName: "クロアチア",
    iso3Code: "HRV",
  ),
  Country(
    continents: [""], isoCode: "HT",
    phoneCode: "509",
    name: "Haiti",
    jpName: "ハイチ",
    iso3Code: "HTI",
  ),
  Country(
    continents: [""], isoCode: "HU",
    phoneCode: "36",
    name: "Hungary",
    jpName: "ハンガリー",
    iso3Code: "HUN",
  ),
  Country(
    continents: [""], isoCode: "ID",
    phoneCode: "62",
    name: "Indonesia",
    jpName: "インドネシア",
    iso3Code: "IDN",
  ),
  Country(
    continents: [""], isoCode: "IE",
    phoneCode: "353",
    name: "Ireland",
    jpName: "アイルランド",
    iso3Code: "IRL",
  ),
  Country(
    continents: [""], isoCode: "IL",
    phoneCode: "972",
    name: "Israel",
    jpName: "イスラエル",
    iso3Code: "ISR",
  ),
  Country(
    continents: [""], isoCode: "IM",
    phoneCode: "44-1624",
    name: "Isle of Man",
    jpName: "マン島",
    iso3Code: "IMN",
  ),
  Country(
    continents: [""], isoCode: "IN",
    phoneCode: "91",
    name: "India",
    jpName: "インド",
    iso3Code: "IND",
  ),
  // Country(
  //   continents: [""], isoCode: "IO",
  //   phoneCode: "246",
  //   name: "British Indian Ocean Territory",
  //   jpName: "イギリス領インド洋地域",
  //   iso3Code: "IOT",
  // ),
  Country(
    continents: [""], isoCode: "IQ",
    phoneCode: "964",
    name: "Iraq",
    jpName: "イラク",
    iso3Code: "IRQ",
  ),
  Country(
    continents: [""], isoCode: "IR",
    phoneCode: "98",
    name: "Iran, Islamic Republic of",
    jpName: "イラン・イスラム共和国",
    iso3Code: "IRN",
  ),
  Country(
    continents: [""], isoCode: "IS",
    phoneCode: "354",
    name: "Iceland",
    jpName: "アイスランド",
    iso3Code: "ISL",
  ),
  Country(
    continents: [""], isoCode: "IT",
    phoneCode: "39",
    name: "Italy",
    jpName: "イタリア",
    iso3Code: "ITA",
  ),
  Country(
    continents: [""], isoCode: "JE",
    phoneCode: "44-1534",
    name: "Jersey",
    jpName: "ジャージー",
    iso3Code: "JEY",
  ),
  Country(
    continents: [""], isoCode: "JM",
    phoneCode: "1-876",
    name: "Jamaica",
    jpName: "ジャマイカ",
    iso3Code: "JAM",
  ),
  Country(
    continents: [""], isoCode: "JO",
    phoneCode: "962",
    name: "Jordan",
    jpName: "ヨルダン",
    iso3Code: "JOR",
  ),
  Country(
    continents: [""], isoCode: "JP",
    phoneCode: "81",
    name: "Japan",
    jpName: "日本",
    iso3Code: "JPN",
  ),
  Country(
    continents: [""], isoCode: "KE",
    phoneCode: "254",
    name: "Kenya",
    jpName: "ケニヤ",
    iso3Code: "KEN",
  ),
  Country(
    continents: [""], isoCode: "KG",
    phoneCode: "996",
    name: "Kyrgyzstan",
    jpName: "キルギス",
    iso3Code: "KGZ",
  ),
  Country(
    continents: [""], isoCode: "KH",
    phoneCode: "855",
    name: "Cambodia",
    jpName: "カンボジア",
    iso3Code: "KHM",
  ),
  Country(
    continents: [""], isoCode: "KI",
    phoneCode: "686",
    name: "Kiribati",
    jpName: "キリバス",
    iso3Code: "KIR",
  ),
  Country(
    continents: [""], isoCode: "KM",
    phoneCode: "269",
    name: "Comoros",
    jpName: "コモロ",
    iso3Code: "COM",
  ),
  Country(
    continents: [""], isoCode: "KN",
    phoneCode: "1-869",
    name: "Saint Kitts and Nevis",
    jpName: "セントクリストファー・ネイビス",
    iso3Code: "KNA",
  ),
  Country(
    continents: [""], isoCode: "KP",
    phoneCode: "850",
    name: "Korea, Democratic People's Republic of",
    jpName: "北朝鮮(朝鮮民主主義人民共和国)",
    iso3Code: "PRK",
  ),
  Country(
    continents: [""], isoCode: "KR",
    phoneCode: "82",
    name: "Korea, Republic of",
    jpName: "韓国(大韓民国)",
    iso3Code: "KOR",
  ),
  Country(
    continents: [""], isoCode: "KW",
    phoneCode: "965",
    name: "Kuwait",
    jpName: "クウェート",
    iso3Code: "KWT",
  ),
  Country(
    continents: [""], isoCode: "KY",
    phoneCode: "1-345",
    name: "Cayman Islands",
    jpName: "ケイマン諸島",
    iso3Code: "CYM",
  ),
  Country(
    continents: [""], isoCode: "KZ",
    phoneCode: "7",
    name: "Kazakhstan",
    jpName: "カザフスタン",
    iso3Code: "KAZ",
  ),
  Country(
    continents: [""], isoCode: "LA",
    phoneCode: "",
    name: "Lao People's Democratic Republic",
    jpName: "ラオス人民民主共和国",
    iso3Code: "LAO",
  ),
  Country(
    continents: [""], isoCode: "LB",
    phoneCode: "961",
    name: "Lebanon",
    jpName: "レバノン",
    iso3Code: "LBN",
  ),
  Country(
    continents: [""], isoCode: "LC",
    phoneCode: "1-758",
    name: "Saint Lucia",
    jpName: "セントルシア",
    iso3Code: "LCA",
  ),
  Country(
    continents: [""], isoCode: "LI",
    phoneCode: "423",
    name: "Liechtenstein",
    jpName: "リヒテンシュタイン",
    iso3Code: "LIE",
  ),
  Country(
    continents: [""], isoCode: "LK",
    phoneCode: "94",
    name: "Sri Lanka",
    jpName: "スリランカ",
    iso3Code: "LKA",
  ),
  Country(
    continents: [""], isoCode: "LR",
    phoneCode: "231",
    name: "Liberia",
    jpName: "リベリア",
    iso3Code: "LBR",
  ),
  Country(
    continents: [""], isoCode: "LS",
    phoneCode: "266",
    name: "Lesotho",
    jpName: "レソト",
    iso3Code: "LSO",
  ),
  Country(
    continents: [""], isoCode: "LT",
    phoneCode: "370",
    name: "Lithuania",
    jpName: "リトアニア",
    iso3Code: "LTU",
  ),
  Country(
    continents: [""], isoCode: "LU",
    phoneCode: "352",
    name: "Luxembourg",
    jpName: "ルクセンブルク",
    iso3Code: "LUX",
  ),
  Country(
    continents: [""], isoCode: "LV",
    phoneCode: "371",
    name: "Latvia",
    jpName: "ラトビア",
    iso3Code: "LVA",
  ),
  Country(
    continents: [""], isoCode: "LY",
    phoneCode: "218",
    name: "Libya",
    jpName: "リビア",
    iso3Code: "LBY",
  ),
  Country(
    continents: [""], isoCode: "MA",
    phoneCode: "212",
    name: "Morocco",
    jpName: "モロッコ",
    iso3Code: "MAR",
  ),
  Country(
    continents: [""], isoCode: "MC",
    phoneCode: "377",
    name: "Monaco",
    jpName: "モナコ",
    iso3Code: "MCO",
  ),
  Country(
    continents: [""], isoCode: "MD",
    phoneCode: "373",
    name: "Moldova, Republic of",
    jpName: "モルドバ共和国",
    iso3Code: "MDA",
  ),
  Country(
    continents: [""], isoCode: "ME",
    phoneCode: "382",
    name: "Montenegro",
    jpName: "モンテネグロ",
    iso3Code: "MNE",
  ),
  Country(
    continents: [""], isoCode: "MF",
    phoneCode: "590",
    name: "Saint Martin",
    jpName: "サン・マルタン（フランス領）",
    iso3Code: "MAF",
  ),
  Country(
    continents: [""], isoCode: "MG",
    phoneCode: "261",
    name: "Madagascar",
    jpName: "マダガスカル",
    iso3Code: "MDG",
  ),
  Country(
    continents: [""], isoCode: "MH",
    phoneCode: "692",
    name: "Marshall Islands",
    jpName: "マーシャル諸島",
    iso3Code: "MHL",
  ),
  Country(
    continents: [""], isoCode: "MK",
    phoneCode: "389",
    name: "Macedonia, the former Yugoslav Republic of",
    jpName: "北マケドニア",
    iso3Code: "MKD",
  ),
  Country(
    continents: [""], isoCode: "ML",
    phoneCode: "223",
    name: "Mali",
    jpName: "マリ",
    iso3Code: "MLI",
  ),
  Country(
    continents: [""], isoCode: "MM",
    phoneCode: "95",
    name: "Myanmar",
    jpName: "ミャンマー",
    iso3Code: "MMR",
  ),
  Country(
    continents: [""], isoCode: "MN",
    phoneCode: "976",
    name: "Mongolia",
    jpName: "モンゴル",
    iso3Code: "MNG",
  ),
  Country(
    continents: [""], isoCode: "MO",
    phoneCode: "853",
    name: "Macao",
    jpName: "マカオ(中国特別行政区)",
    iso3Code: "MAC",
  ),
  Country(
    continents: [""], isoCode: "MP",
    phoneCode: "1-670",
    name: "Northern Mariana Islands",
    jpName: "北マリアナ諸島",
    iso3Code: "MNP",
  ),
  Country(
    continents: [""], isoCode: "MQ",
    phoneCode: "596",
    name: "Martinique",
    jpName: "マルティニーク",
    iso3Code: "MTQ",
  ),
  Country(
    continents: [""], isoCode: "MR",
    phoneCode: "222",
    name: "Mauritania",
    jpName: "モーリタニア",
    iso3Code: "MRT",
  ),
  Country(
    continents: [""], isoCode: "MS",
    phoneCode: "1-664",
    name: "Montserrat",
    jpName: "モントセラト",
    iso3Code: "MSR",
  ),
  Country(
    continents: [""], isoCode: "MT",
    phoneCode: "356",
    name: "Malta",
    jpName: "マルタ",
    iso3Code: "MLT",
  ),
  Country(
    continents: [""], isoCode: "MU",
    phoneCode: "230",
    name: "Mauritius",
    jpName: "モーリシャス",
    iso3Code: "MUS",
  ),
  Country(
    continents: [""], isoCode: "MV",
    phoneCode: "960",
    name: "Maldives",
    jpName: "モルディブ",
    iso3Code: "MDV",
  ),
  Country(
    continents: [""], isoCode: "MW",
    phoneCode: "265",
    name: "Malawi",
    jpName: "マラウイ",
    iso3Code: "MWI",
  ),
  Country(
    continents: [""], isoCode: "MX",
    phoneCode: "52",
    name: "Mexico",
    jpName: "メキシコ",
    iso3Code: "MEX",
  ),
  Country(
    continents: [""], isoCode: "MY",
    phoneCode: "60",
    name: "Malaysia",
    jpName: "マレーシア",
    iso3Code: "MYS",
  ),
  Country(
    continents: [""], isoCode: "MZ",
    phoneCode: "258",
    name: "Mozambique",
    jpName: "モザンビーク",
    iso3Code: "MOZ",
  ),
  Country(
    continents: [""], isoCode: "NA",
    phoneCode: "264",
    name: "Namibia",
    jpName: "ナミビア",
    iso3Code: "NAM",
  ),
  Country(
    continents: [""], isoCode: "NC",
    phoneCode: "687",
    name: "New Caledonia",
    jpName: "ニューカレドニア",
    iso3Code: "NCL",
  ),
  Country(
    continents: [""], isoCode: "NE",
    phoneCode: "227",
    name: "Niger",
    jpName: "ニジェール",
    iso3Code: "NER",
  ),
  Country(
    continents: [""], isoCode: "NF",
    phoneCode: "672",
    name: "Norfolk Island",
    jpName: "ノーフォーク島",
    iso3Code: "NFK",
  ),
  Country(
    continents: [""], isoCode: "NG",
    phoneCode: "234",
    name: "Nigeria",
    jpName: "ナイジェリア",
    iso3Code: "NGA",
  ),
  Country(
    continents: [""], isoCode: "NI",
    phoneCode: "505",
    name: "Nicaragua",
    jpName: "ニカラグア",
    iso3Code: "NIC",
  ),
  Country(
    continents: [""], isoCode: "NL",
    phoneCode: "31",
    name: "Netherlands",
    jpName: "オランダ",
    iso3Code: "NLD",
  ),
  Country(
    continents: [""], isoCode: "NO",
    phoneCode: "47",
    name: "Norway",
    jpName: "ノルウェー",
    iso3Code: "NOR",
  ),
  Country(
    continents: [""], isoCode: "NP",
    phoneCode: "977",
    name: "Nepal",
    jpName: "ネパール",
    iso3Code: "NPL",
  ),
  Country(
    continents: [""], isoCode: "NR",
    phoneCode: "674",
    name: "Nauru",
    jpName: "ナウル",
    iso3Code: "NRU",
  ),
  Country(
    continents: [""], isoCode: "NU",
    phoneCode: "683",
    name: "Niue",
    jpName: "ニウエ",
    iso3Code: "NIU",
  ),
  Country(
    continents: [""], isoCode: "NZ",
    phoneCode: "64",
    name: "New Zealand",
    jpName: "ニュージーランド",
    iso3Code: "NZL",
  ),
  Country(
    continents: [""], isoCode: "OM",
    phoneCode: "968",
    name: "Oman",
    jpName: "オマーン",
    iso3Code: "OMN",
  ),
  Country(
    continents: [""], isoCode: "PA",
    phoneCode: "507",
    name: "Panama",
    jpName: "パナマ",
    iso3Code: "PAN",
  ),
  Country(
    continents: [""], isoCode: "PE",
    phoneCode: "51",
    name: "Peru",
    jpName: "ペルー",
    iso3Code: "PER",
  ),
  Country(
    continents: [""], isoCode: "PF",
    phoneCode: "689",
    name: "French Polynesia",
    jpName: "フランス領ポリネシア",
    iso3Code: "PYF",
  ),
  Country(
    continents: [""], isoCode: "PG",
    phoneCode: "675",
    name: "Papua New Guinea",
    jpName: "パプアニューギニア",
    iso3Code: "PNG",
  ),
  Country(
    continents: [""], isoCode: "PH",
    phoneCode: "63",
    name: "Philippines",
    jpName: "フィリピン",
    iso3Code: "PHL",
  ),
  Country(
    continents: [""], isoCode: "PK",
    phoneCode: "92",
    name: "Pakistan",
    jpName: "パキスタン",
    iso3Code: "PAK",
  ),
  Country(
    continents: [""], isoCode: "PL",
    phoneCode: "48",
    name: "Poland",
    jpName: "ポーランド",
    iso3Code: "POL",
  ),
  Country(
    continents: [""], isoCode: "PM",
    phoneCode: "508",
    name: "Saint Pierre and Miquelon",
    jpName: "サンピエール島・ミクロン島",
    iso3Code: "SPM",
  ),
  Country(
    continents: [""], isoCode: "PN",
    phoneCode: "64",
    name: "Pitcairn",
    jpName: "ピトケアン",
    iso3Code: "PCN",
  ),
  Country(
    continents: [""], isoCode: "PR",
    phoneCode: "1-787",
    name: "Puerto Rico",
    jpName: "プエルトリコ",
    iso3Code: "PRI",
  ),
  Country(
    continents: [""], isoCode: "PS",
    phoneCode: "970",
    name: "Palestine",
    jpName: "パレスチナ",
    iso3Code: "PSE",
  ),
  Country(
    continents: [""], isoCode: "PT",
    phoneCode: "351",
    name: "Portugal",
    jpName: "ポルトガル",
    iso3Code: "PRT",
  ),
  Country(
    continents: [""], isoCode: "PW",
    phoneCode: "680",
    name: "Palau",
    jpName: "パラオ",
    iso3Code: "PLW",
  ),
  Country(
    continents: [""], isoCode: "PY",
    phoneCode: "595",
    name: "Paraguay",
    jpName: "パラグアイ",
    iso3Code: "PRY",
  ),
  Country(
    continents: [""], isoCode: "QA",
    phoneCode: "974",
    name: "Qatar",
    jpName: "カタール",
    iso3Code: "QAT",
  ),
  Country(
    continents: [""], isoCode: "RE",
    phoneCode: "262",
    name: "Réunion",
    jpName: "レユニオン",
    iso3Code: "REU",
  ),
  Country(
    continents: [""], isoCode: "RO",
    phoneCode: "40",
    name: "Romania",
    jpName: "ルーマニア",
    iso3Code: "ROU",
  ),
  Country(
    continents: [""], isoCode: "RS",
    phoneCode: "381",
    name: "Serbia",
    jpName: "セルビア",
    iso3Code: "SRB",
  ),
  Country(
    continents: [""], isoCode: "RU",
    phoneCode: "7",
    name: "Russian Federation",
    jpName: "ロシア連邦",
    iso3Code: "RUS",
  ),
  Country(
    continents: [""], isoCode: "RW",
    phoneCode: "250",
    name: "Rwanda",
    jpName: "ルワンダ",
    iso3Code: "RWA",
  ),
  Country(
    continents: [""], isoCode: "SA",
    phoneCode: "966",
    name: "Saudi Arabia",
    jpName: "サウジアラビア",
    iso3Code: "SAU",
  ),
  Country(
    continents: [""], isoCode: "SB",
    phoneCode: "677",
    name: "Solomon Islands",
    jpName: "ソロモン諸島",
    iso3Code: "SLB",
  ),
  Country(
    continents: [""], isoCode: "SC",
    phoneCode: "248",
    name: "Seychelles",
    jpName: "セーシェル",
    iso3Code: "SYC",
  ),
  Country(
    continents: [""], isoCode: "SD",
    phoneCode: "249",
    name: "Sudan",
    jpName: "スーダン",
    iso3Code: "SDN",
  ),
  Country(
    continents: [""], isoCode: "SE",
    phoneCode: "46",
    name: "Sweden",
    jpName: "スウェーデン",
    iso3Code: "SWE",
  ),
  Country(
    continents: [""], isoCode: "SG",
    phoneCode: "65",
    name: "Singapore",
    jpName: "シンガポール",
    iso3Code: "SGP",
  ),
  // Country(
  //   continents: [""], isoCode: "SH",
  //   phoneCode: "290",
  //   name: "Saint Helena, Ascension and Tristan da Cunha",
  //   jpName: "セントヘレナ・アセンションおよびトリスタンダクーニャ",
  //   iso3Code: "SHN",
  // ),
  Country(
    continents: [""], isoCode: "SI",
    phoneCode: "386",
    name: "Slovenia",
    jpName: "スロベニア",
    iso3Code: "SVN",
  ),
  Country(
    continents: [""], isoCode: "SJ",
    phoneCode: "47",
    name: "Svalbard and Jan Mayen Islands",
    jpName: "スヴァールバル諸島およびヤンマイエン島",
    iso3Code: "SJM",
  ),
  Country(
    continents: [""], isoCode: "SK",
    phoneCode: "421",
    name: "Slovakia",
    jpName: "スロバキア",
    iso3Code: "SVK",
  ),
  Country(
    continents: [""], isoCode: "SL",
    phoneCode: "232",
    name: "Sierra Leone",
    jpName: "シエラレオネ",
    iso3Code: "SLE",
  ),
  Country(
    continents: [""], isoCode: "SM",
    phoneCode: "378",
    name: "San Marino",
    jpName: "サンマリノ",
    iso3Code: "SMR",
  ),
  Country(
    continents: [""], isoCode: "SN",
    phoneCode: "221",
    name: "Senegal",
    jpName: "セネガル",
    iso3Code: "SEN",
  ),
  Country(
    continents: [""], isoCode: "SO",
    phoneCode: "252",
    name: "Somalia",
    jpName: "ソマリア",
    iso3Code: "SOM",
  ),
  Country(
    continents: [""], isoCode: "SR",
    phoneCode: "597",
    name: "Suriname",
    jpName: "スリナム",
    iso3Code: "SUR",
  ),
  Country(
    continents: [""], isoCode: "SS",
    phoneCode: "211",
    name: "South Sudan",
    jpName: "南スーダン",
    iso3Code: "SSD",
  ),
  Country(
    continents: [""], isoCode: "ST",
    phoneCode: "239",
    name: "Sao Tome and Principe",
    jpName: "サントメ・プリンシペ",
    iso3Code: "STP",
  ),
  Country(
    continents: [""], isoCode: "SV",
    phoneCode: "503",
    name: "El Salvador",
    jpName: "エルサルバドル",
    iso3Code: "SLV",
  ),
  Country(
    continents: [""], isoCode: "SX",
    phoneCode: "1-721",
    name: "Sint Maarten (Dutch part)",
    jpName: "シント・マールテン",
    iso3Code: "SXM",
  ),
  Country(
    continents: [""], isoCode: "SY",
    phoneCode: "963",
    name: "Syrian Arab Republic",
    jpName: "シリア・アラブ共和国",
    iso3Code: "SYR",
  ),
  Country(
    continents: [""], isoCode: "SZ",
    phoneCode: "268",
    name: "Swaziland",
    jpName: "エスワティニ",
    iso3Code: "SWZ",
  ),
  Country(
    continents: [""], isoCode: "TC",
    phoneCode: "1-649",
    name: "Turks and Caicos Islands",
    jpName: "タークス・カイコス諸島",
    iso3Code: "TCA",
  ),
  Country(
    continents: [""], isoCode: "TD",
    phoneCode: "235",
    name: "Chad",
    jpName: "チャド",
    iso3Code: "TCD",
  ),
  Country(
    continents: [""], isoCode: "TF",
    phoneCode: "262",
    name: "French Southern Territories",
    jpName: "フランス領南方・南極地域",
    iso3Code: "ATF",
  ),
  Country(
    continents: [""], isoCode: "TG",
    phoneCode: "228",
    name: "Togo",
    jpName: "トーゴ",
    iso3Code: "TGO",
  ),
  Country(
    continents: [""], isoCode: "TH",
    phoneCode: "66",
    name: "Thailand",
    jpName: "タイ",
    iso3Code: "THA",
  ),
  Country(
    continents: [""], isoCode: "TJ",
    phoneCode: "992",
    name: "Tajikistan",
    jpName: "タジキスタン",
    iso3Code: "TJK",
  ),
  Country(
    continents: [""], isoCode: "TK",
    phoneCode: "690",
    name: "Tokelau",
    jpName: "トケラウ",
    iso3Code: "TKL",
  ),
  Country(
    continents: [""], isoCode: "TL",
    phoneCode: "670",
    name: "Timor-Leste",
    jpName: "東ティモール",
    iso3Code: "TLS",
  ),
  Country(
    continents: [""], isoCode: "TM",
    phoneCode: "993",
    name: "Turkmenistan",
    jpName: "トルクメニスタン",
    iso3Code: "TKM",
  ),
  Country(
    continents: [""], isoCode: "TN",
    phoneCode: "216",
    name: "Tunisia",
    jpName: "チュニジア",
    iso3Code: "TUN",
  ),
  Country(
    continents: [""], isoCode: "TO",
    phoneCode: "676",
    name: "Tonga",
    jpName: "トンガ",
    iso3Code: "TON",
  ),
  Country(
    continents: [""], isoCode: "TR",
    phoneCode: "90",
    name: "Turkey",
    jpName: "トルコ",
    iso3Code: "TUR",
  ),
  Country(
    continents: [""], isoCode: "TT",
    phoneCode: "1-868",
    name: "Trinidad and Tobago",
    jpName: "トリニダード・トバゴ",
    iso3Code: "TTO",
  ),
  Country(
    continents: [""], isoCode: "TV",
    phoneCode: "688",
    name: "Tuvalu",
    jpName: "ツバル",
    iso3Code: "TUV",
  ),
  Country(
    continents: [""], isoCode: "TW",
    phoneCode: "886",
    name: "Taiwan",
    jpName: "中華民国(中国台湾省)",
    iso3Code: "TWN",
  ),
  Country(
    continents: [""], isoCode: "TZ",
    phoneCode: "255",
    name: "Tanzania, United Republic of",
    jpName: "タンザニア",
    iso3Code: "TZA",
  ),
  Country(
    continents: [""], isoCode: "UA",
    phoneCode: "380",
    name: "Ukraine",
    jpName: "ウクライナ",
    iso3Code: "UKR",
  ),
  Country(
    continents: [""], isoCode: "UG",
    phoneCode: "256",
    name: "Uganda",
    jpName: "ウガンダ",
    iso3Code: "UGA",
  ),
  Country(
    continents: [""], isoCode: "UM",
    phoneCode: "1",
    name: "US Minor Outlying Islands",
    jpName: "合衆国領有小離島",
    iso3Code: "UMI",
  ),
  Country(
    continents: [""], isoCode: "US",
    phoneCode: "1",
    name: "United States",
    jpName: "アメリカ合衆国",
    iso3Code: "USA",
  ),
  Country(
    continents: [""], isoCode: "UY",
    phoneCode: "598",
    name: "Uruguay",
    jpName: "ウルグアイ",
    iso3Code: "URY",
  ),
  Country(
    continents: [""], isoCode: "UZ",
    phoneCode: "998",
    name: "Uzbekistan",
    jpName: "ウズベキスタン",
    iso3Code: "UZB",
  ),
  Country(
    continents: [""], isoCode: "VA",
    phoneCode: "379",
    name: "Holy See (Vatican City State)",
    jpName: "バチカン市国",
    iso3Code: "VAT",
  ),
  Country(
    continents: [""], isoCode: "VC",
    phoneCode: "1-784",
    name: "Saint Vincent and the Grenadines",
    jpName: "セントビンセントおよびグレナディーン諸島",
    iso3Code: "VCT",
  ),
  Country(
    continents: [""], isoCode: "VE",
    phoneCode: "58",
    name: "Venezuela, Bolivarian Republic of",
    jpName: "ベネズエラ・ボリバル共和国",
    iso3Code: "VEN",
  ),
  Country(
    continents: [""], isoCode: "VG",
    phoneCode: "1-284",
    name: "Virgin Islands, British",
    jpName: "イギリス領ヴァージン諸島",
    iso3Code: "VGB",
  ),
  Country(
    continents: [""], isoCode: "VI",
    phoneCode: "1-340",
    name: "Virgin Islands, U.S.",
    jpName: "アメリカ領ヴァージン諸島",
    iso3Code: "VIR",
  ),
  Country(
    continents: [""], isoCode: "VN",
    phoneCode: "84",
    name: "Vietnam",
    jpName: "ベトナム",
    iso3Code: "VNM",
  ),
  Country(
    continents: [""], isoCode: "VU",
    phoneCode: "678",
    name: "Vanuatu",
    jpName: "バヌアツ",
    iso3Code: "VUT",
  ),
  Country(
    continents: [""], isoCode: "WF",
    phoneCode: "681",
    name: "Wallis and Futuna Islands",
    jpName: "ウォリス・フツナ",
    iso3Code: "WLF",
  ),
  Country(
    continents: [""], isoCode: "XK",
    phoneCode: "383",
    name: "Kosovo",
    jpName: "コソボ",
    iso3Code: "KOS",
  ),
  Country(
    continents: [""], isoCode: "WS",
    phoneCode: "685",
    name: "Samoa",
    jpName: "サモア",
    iso3Code: "WSM",
  ),
  Country(
    continents: [""], isoCode: "YE",
    phoneCode: "967",
    name: "Yemen",
    jpName: "イエメン",
    iso3Code: "YEM",
  ),
  Country(
    continents: [""], isoCode: "YT",
    phoneCode: "262",
    name: "Mayotte",
    jpName: "マヨット",
    iso3Code: "MYT",
  ),
  Country(
    continents: [""], isoCode: "ZA",
    phoneCode: "27",
    name: "South Africa",
    jpName: "南アフリカ",
    iso3Code: "ZAF",
  ),
  Country(
    continents: [""], isoCode: "ZM",
    phoneCode: "260",
    name: "Zambia",
    jpName: "ザンビア",
    iso3Code: "ZMB",
  ),
  Country(
    continents: [""], isoCode: "ZW",
    phoneCode: "263",
    name: "Zimbabwe",
    jpName: "ジンバブエ",
    iso3Code: "ZWE",
  ),
];
